#!/usr/bin/env python3
"""Строит каталог цен OpenRouter из его публичного API.

ЗАЧЕМ ЭТО СКРИПТ, А НЕ ТАБЛИЦА РУКАМИ

Заявление об экономии проверяемо ровно настолько, насколько проверяема цена,
из которой оно посчитано. Прайс NVIDIA NIM для hosted-эндпоинтов не
публикуется вовсе (доступ бесплатный для прототипирования, прод —
лицензия NVIDIA AI Enterprise за GPU в год), поэтому датировать цены «по
прайсу того дня» там нечем. OpenRouter отдаёт цены машиночитаемо и без
авторизации::

    GET https://openrouter.ai/api/v1/models

Любой посторонний запускает этот скрипт, получает те же числа и
пересчитывает экономию сам, не доверяя аудитору.

СВОБОДНЫЙ ПРОГОН, ПЛАТНЫЙ ПРАЙС — И ПОЧЕМУ ЭТО НАДО ГОВОРИТЬ ВСЛУХ

У OpenRouter один и тот же вес доступен двумя маршрутами: ``<id>`` (платный,
с опубликованной ценой) и ``<id>:free`` (бесплатный, с лимитом 20 запросов
в минуту). Прогон идёт по ``:free`` — фактические затраты нулевые для обеих
конфигураций, и «экономия» из них не считается никак.

Поэтому в каталог кладётся:
  model_name — идентификатор ``:free``, тот, который реально вызывается;
  цены       — опубликованный лист платного аналога тех же весов;
  priced_as  — какой именно платный идентификатор дал цену.

Заявление в чеке тогда читается точно: качество измерено на этих весах,
разница в стоимости посчитана по опубликованному прайсу OpenRouter на
указанную дату. Это контрфактный расчёт по листовым ценам, а не выставленный
счёт, и называть его надо именно так.

Остаточная оговорка, которую нельзя прятать: бесплатный маршрут может
обслуживаться другим провайдером и другой квантизацией, чем платный. Значит
измеренное качество не гарантированно совпадает с качеством платного
маршрута. Это меньший разрыв, чем цена без источника, но он есть.

РЕЖИМ ВТОРОЙ: ПРОГОН ГДЕ ЕСТЬ КВОТА, ЦЕНА ИЗ ПУБЛИЧНОГО ЛИСТА

``--run-provider nvidia-nim`` берёт эндпоинты из существующего NIM-каталога
(как звать модель) и заменяет в них только цены — опубликованными ценами
OpenRouter на те же открытые веса (сколько это стоит). Нужен он там, где
суточная квота OpenRouter не позволяет прогон, а ключ NIM есть.

Сопоставление имён строгое, не нечёткое: берётся последний сегмент
идентификатора, отбрасывается версионный суффикс вида ``-v0.1``, и требуется
РОВНО одно совпадение среди платных моделей OpenRouter. Ноль совпадений —
модель пропускается с предупреждением; больше одного — отказ. Молча
подставить цену похожей модели нельзя: именно из такой подстановки берутся
заявления об экономии, которые потом не сходятся.

Разрыв этого режима называем прямо: прогон идёт у одного провайдера, цена
взята у другого. Обосновано это тем, что веса — одни и те же выпущенные
чекпоинты открытых моделей, а NIM пер-токенного прайса не публикует вовсе.
Но в чеке это обязано стоять открытым текстом, иначе читатель решит, что
измеренное и оценённое — одно и то же развёртывание.

ЗАПУСК

    python scripts/fetch_openrouter_prices.py
    python scripts/fetch_openrouter_prices.py --run-provider nvidia-nim
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import re
import sys
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any, Optional

REPO_ROOT = Path(__file__).resolve().parent.parent

MODELS_URL = "https://openrouter.ai/api/v1/models"
BASE_URL = "https://openrouter.ai/api/v1"
API_KEY_ENV = "OPENROUTER_API_KEY"

NOTE = (
    "Generated by scripts/fetch_openrouter_prices.py from OpenRouter's public "
    "models API — no authentication, so anyone can regenerate it and re-derive "
    "any savings claim computed from it. model_name is the ':free' route that "
    "is actually called; the prices are the published list prices of the paid "
    "route over the same weights, named in 'priced_as'. Actual spend on ':free' "
    "is zero for every entry, so a savings figure computed here is a "
    "counterfactual at list prices, not a billed amount. Caveat: the free route "
    "may be served by a different provider or quantization than the paid one."
)

NOTE_NIM = (
    "Generated by scripts/fetch_openrouter_prices.py --run-provider nvidia-nim. "
    "Endpoints (how to call the model) come from flows/model_catalog.json; the "
    "prices come from OpenRouter's public models API for the same open-weight "
    "checkpoints, named in 'priced_as'. NVIDIA publishes no per-token price for "
    "its hosted NIM endpoints, so the price basis is a named, dated, fetchable "
    "third-party list. DISCLOSE THIS: the audit runs on NVIDIA NIM but is priced "
    "at OpenRouter list rates — same released weights, different serving. Anyone "
    "can regenerate this file and re-derive any savings claim computed from it."
)


def fetch_models(url: str) -> list[dict[str, Any]]:
    try:
        with urllib.request.urlopen(url, timeout=60) as response:
            payload = json.load(response)
    except (urllib.error.URLError, TimeoutError) as exc:
        raise SystemExit(f"FATAL: cannot fetch {url}: {exc}") from exc

    models = payload.get("data")

    if not isinstance(models, list) or not models:
        raise SystemExit(f"FATAL: {url} returned no models")

    return models


def _price_per_million(pricing: dict[str, Any], key: str) -> Optional[float]:
    """OpenRouter отдаёт цену за токен строкой; каталог хранит за 1M."""
    raw = pricing.get(key)

    if raw is None:
        return None

    try:
        return round(float(raw) * 1e6, 6)
    except (TypeError, ValueError):
        return None


def _tier(rank: int, total: int) -> str:
    """Три равные полосы по цене входа: Autopilot отбирает кандидатов по tier."""
    if total <= 1:
        return "mid"

    position = rank / (total - 1)

    if position <= 1 / 3:
        return "premium"

    if position <= 2 / 3:
        return "mid"

    return "economy"


def build_entries(models: list[dict[str, Any]]) -> list[dict[str, Any]]:
    by_id: dict[str, dict[str, Any]] = {}

    for model in models:
        model_id = model.get("id")

        if isinstance(model_id, str):
            by_id[model_id] = model

    collected: list[tuple[float, float, str, str, dict[str, Any]]] = []

    for model_id, model in by_id.items():
        if not model_id.endswith(":free"):
            continue

        paid_id = model_id[: -len(":free")]
        paid = by_id.get(paid_id)

        if paid is None:
            continue

        pricing = paid.get("pricing") or {}
        input_price = _price_per_million(pricing, "prompt")
        output_price = _price_per_million(pricing, "completion")

        # Нулевая или отсутствующая цена платного маршрута не годится как
        # основа заявления: считать экономию было бы не из чего.
        if not input_price or output_price is None:
            continue

        collected.append((input_price, output_price, model_id, paid_id, model))

    # По убыванию цены входа: premium сверху, economy снизу.
    collected.sort(key=lambda row: (-row[0], row[2]))
    total = len(collected)
    entries: list[dict[str, Any]] = []

    for rank, (input_price, output_price, model_id, paid_id, model) in enumerate(collected):
        architecture = model.get("architecture") or {}
        entries.append(
            {
                "model_name": model_id,
                "priced_as": paid_id,
                "provider": "openrouter",
                "base_url": BASE_URL,
                "api_key_env": API_KEY_ENV,
                "input_token_usd_per_m": input_price,
                "output_token_usd_per_m": output_price,
                "tier": _tier(rank, total),
                "context_window": model.get("context_length"),
                "tags": sorted(
                    set(
                        (model.get("supported_parameters") or [])
                    )
                    & {"reasoning", "tools", "structured_outputs"}
                )
                or ["chat"],
                "modality": architecture.get("modality"),
            }
        )

    return entries


def _segment(model_id: str) -> str:
    """Последний сегмент без версионного суффикса: llama-3.3-70b-instruct."""
    stem = model_id.split("/")[-1]

    return re.sub(r"-v\d+(\.\d+)*$", "", stem)


def build_nim_entries(
    models: list[dict[str, Any]], nim_catalog: dict[str, Any]
) -> tuple[list[dict[str, Any]], list[str]]:
    """Эндпоинты NIM с ценами OpenRouter. Возвращает (записи, пропущенные)."""
    by_segment: dict[str, list[dict[str, Any]]] = {}

    for model in models:
        model_id = model.get("id")

        if not isinstance(model_id, str) or model_id.endswith(":free"):
            continue

        by_segment.setdefault(_segment(model_id), []).append(model)

    entries: list[dict[str, Any]] = []
    skipped: list[str] = []

    for source in nim_catalog.get("models", []):
        nim_id = source.get("model_name")

        if not isinstance(nim_id, str):
            continue

        matches = by_segment.get(_segment(nim_id), [])

        if len(matches) > 1:
            ids = ", ".join(str(m.get("id")) for m in matches)
            raise SystemExit(
                f"FATAL: {nim_id} matches several OpenRouter models ({ids}). "
                "Refusing to guess which list price applies."
            )

        if not matches:
            skipped.append(nim_id)
            continue

        paid = matches[0]
        pricing = paid.get("pricing") or {}
        input_price = _price_per_million(pricing, "prompt")
        output_price = _price_per_million(pricing, "completion")

        if not input_price or output_price is None:
            skipped.append(nim_id)
            continue

        entry = dict(source)
        entry["input_token_usd_per_m"] = input_price
        entry["output_token_usd_per_m"] = output_price
        entry["priced_as"] = paid.get("id")
        entries.append(entry)

    entries.sort(key=lambda e: (-float(e["input_token_usd_per_m"]), str(e["model_name"])))
    total = len(entries)

    for rank, entry in enumerate(entries):
        entry["tier"] = _tier(rank, total)

    return entries, skipped


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default=None)
    parser.add_argument("--url", default=MODELS_URL)
    parser.add_argument(
        "--run-provider",
        choices=("openrouter-free", "nvidia-nim"),
        default="openrouter-free",
        help="Где идёт прогон. Цены в обоих режимах — из публичного API OpenRouter.",
    )
    parser.add_argument(
        "--nim-catalog",
        default=str(REPO_ROOT / "flows" / "model_catalog.json"),
        help="Каталог, из которого берутся эндпоинты для режима nvidia-nim.",
    )
    parser.add_argument(
        "--as-of",
        default=None,
        help="Дата снимка цен (YYYY-MM-DD). По умолчанию — сегодня.",
    )
    args = parser.parse_args()

    as_of = args.as_of or dt.date.today().isoformat()
    models = fetch_models(args.url)
    skipped: list[str] = []

    if args.run_provider == "nvidia-nim":
        nim_catalog = json.loads(Path(args.nim_catalog).read_text(encoding="utf-8"))
        entries, skipped = build_nim_entries(models, nim_catalog)
        note = NOTE_NIM
        default_out = REPO_ROOT / "flows" / "nim_priced_catalog.json"
        version_prefix = "nim-or"
    else:
        entries = build_entries(models)
        note = NOTE
        default_out = REPO_ROOT / "flows" / "openrouter_catalog.json"
        version_prefix = "or"

    if not entries:
        print(
            "FATAL: no model resolved to a published price — there is no "
            "verifiable price basis to build a catalog on.",
            file=sys.stderr,
        )
        return 2

    catalog = {
        "_note": note,
        "_source": args.url,
        "prices_as_of": as_of,
        "catalog_version": f"{version_prefix}-{as_of}",
        "models": entries,
    }

    out_path = Path(args.out) if args.out else default_out
    out_path.write_text(
        json.dumps(catalog, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )

    print(f"source     : {args.url} ({len(models)} models)")
    print(f"run on     : {args.run_provider}")
    print(f"catalog    : {len(entries)} entries -> {out_path}")
    print(f"prices_as_of: {as_of}   catalog_version: {version_prefix}-{as_of}")

    if skipped:
        print(
            f"skipped    : {len(skipped)} model(s) with no published counterpart "
            f"— {', '.join(skipped)}"
        )

    print()
    print(f"{'in $/M':>8} {'out $/M':>8}  {'tier':<8} model_name")

    for entry in entries:
        print(
            f"{entry['input_token_usd_per_m']:8.3f} "
            f"{entry['output_token_usd_per_m']:8.3f}  "
            f"{entry['tier']:<8} {entry['model_name']}"
        )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
